//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForgottenTyrants
{
    
    /// <summary>
    /// Use this type in place of scene names in code / scripts.
    /// </summary>
    /// <example>
    /// <code>
    /// SceneManager.LoadScene(Scene.SampleScene); 
    /// </code>
    /// </example>
    public sealed class Scene
    {
        public const string Bootstrapper = "Bootstrapper";
        public const string StartMenu = "Start Menu";
        public const string UICharacterSelection = "UI Character Selection";
        public const string PruebasIvan = "PruebasIvan";
        public const string PruebasDiego = "PruebasDiego";
        public const string MainMenu = "MainMenu";
        public const string CharacterSelect = "CharacterSelect";
        public const string Gameplay = "Gameplay";
        public const string GameplayMap = "GameplayMap";
        /// <summary>
        /// Use this type in place of scene names in code / scripts.
        /// </summary>
        /// <example>
        /// <code>
        /// SceneManager.LoadScene(Scene.BuildIndex.SampleScene + 1); 
        /// </code>
        /// </example>
        public sealed class BuildIndex
        {
            public const int Bootstrapper = 0;
            public const int StartMenu = 1;
            public const int UICharacterSelection = 2;
            public const int PruebasIvan = 3;
            public const int PruebasDiego = 4;
            public const int MainMenu = 5;
            public const int CharacterSelect = 6;
            public const int Gameplay = 7;
            public const int GameplayMap = 8;
        }
    }
}
